namespace: "dgarcia-riq"
name: "cumulus_linux_roles"
version: "1.0.0"
readme: "README.md"
license: "Apache-2.0"
authors:
    - "Cumulus Networks"
tags:
    - network
    - evpn
    - vxlan
    - networking
repository: "https://github.com/dgarcia-riq/cumulus_ansible_modules.git"
